[package]
name = "compare-test"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lz4 = "1.23.2"
rayon = "1.5.1"
structopt = "0.3.21"
