[package]
name = "ggcat-cpp-bindings"
version = "2.0.0"
edition = "2021"

[lib]
crate-type = ["staticlib"]

[dependencies]
cxx = "1.0.124"
ggcat-api = { version = "2.0.0", path = "../api" }
static_assertions = "1.1.0"

[build-dependencies]
cxx-build = "1.0.124"
